[package]
name = "unifed-fedml"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "Example UniFed protocol."
language = "python"
install_script = """
if { conda env list | grep 'colink-protocol-unifed-fedml'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedml
fi
conda create -n colink-protocol-unifed-fedml python=3.10 -y
conda activate colink-protocol-unifed-fedml
pip install fedml==0.8.2
pip install .
"""
entrypoint = """
conda activate colink-protocol-unifed-fedml
unifed-fedml
"""
