[package]
name = "unifed-fedml"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "Example UniFed protocol."
language = "python"
install_script = """
if { conda env list | grep 'colink-protocol-unifed-fedml'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedml
fi
conda create -n colink-protocol-unifed-fedml python=3.9 -y
conda activate colink-protocol-unifed-fedml
pip install .
pip install scikit-learn==1.1.3
pip install flbenchmark==0.1.3
pip install urllib3==1.26.11
git clone https://github.com/FedML-AI/FedML.git
cd FedML
git checkout 7d53a4f39ee41a9769560f3255ad4f6eddd1a01f
cd python
python setup.py install
"""
entrypoint = """
conda activate colink-protocol-unifed-fedml
unifed-fedml
"""
