common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  using_mlops: false
  random_seed: 0

data_args:
  dataset: "breast_horizontal"
  data_cache_dir: data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list:
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 100
  epochs: 1
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.01
  weight_decay: 0.

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 1
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "GRPC"
  grpc_ipconfig_path: src/unifed/frameworks/fedml/config/grpc_ipconfig.csv

tracking_args:
  enable_wandb: true
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg